---
- hosts: all
  become: true
  vars:
    ldap_auth_ldap_0_namename: vpn.example.com
    ldap_auth_ldap_0_server_0_hostserver_0: ldap.example.com
    auth_ldap_0_bind_dn: administrator@ldap.example.com
    auth_ldap_0_bind_pw: superstrongpassword
    auth_ldap_0_users_base_dn: cn=Users,dc=ldap,dc=example,dc=com
    auth_ldap_0_uname_attr: sAMAccountName
    auth_ldap_0_use_ssl: always
    auth_module_type: ldap
  vars_files:
    - test-cert.yml
  tasks:
  - include: tasks/main.yml
  handlers:
  - include: handlers/main.yml